name: otus-log-analyzer-ci
on:
  push:

jobs:
  Daily-Run:
    runs-on: ubuntu-latest
    steps:
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: install poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.3
          virtualenvs-create: true
          virtualenvs-in-project: true
      - run: poetry install --no-interaction --no-root
      - run: poetry install --no-interaction
      - run: poetry run pytest
